const getUser = async (req, res) => {
  try {
    
  } catch (error) {

  }
};
